language: python
python:
  - "3.5"
  - "3.6"
  - "nightly"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
script:
  - pytest3 # or py.test for Python versions 3.5 and below